# Generated by Django 6.0.4 on 2026-04-23 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telemetria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('velocidad_kmh', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('km_acumulado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nivel_combustible', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura_motor', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contrato')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetrias', to='vehicles.vehiculo')),
            ],
            options={
                'db_table': 'fleet_telemetria',
                'indexes': [models.Index(fields=['vehiculo', '-timestamp'], name='fleet_telem_vehicul_b1f5a7_idx'), models.Index(fields=['contrato'], name='fleet_telem_contrat_134b46_idx')],
            },
        ),
    ]
