# Generated by Django 6.0.4 on 2026-04-23 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(blank=True, default='', max_length=200)),
                ('num_licencia', models.CharField(max_length=30, unique=True)),
                ('categoria_licencia', models.CharField(default='B1', max_length=10)),
                ('fecha_venc_licencia', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=20)),
                ('horas_hoy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('horas_totales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('limite_horas_dia', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fleet_conductor',
                'indexes': [models.Index(fields=['estado'], name='fleet_condu_estado_7bc17e_idx'), models.Index(fields=['cedula'], name='fleet_condu_cedula_b705bc_idx')],
            },
        ),
    ]
