# Generated by Django 6.0.4 on 2026-04-23 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(blank=True, default='', max_length=80)),
                ('anio', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('tipo', models.CharField(choices=[('particular', 'Particular'), ('bus', 'Bus'), ('camion', 'Camión'), ('motocicleta', 'Motocicleta'), ('furgon', 'Furgón')], default='particular', max_length=20)),
                ('capacidad', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('color', models.CharField(blank=True, max_length=40, null=True)),
                ('numero_motor', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_chasis', models.CharField(blank=True, max_length=50, null=True)),
                ('km_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('km_acumulado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_renta', 'En Renta'), ('mantenimiento', 'Mantenimiento'), ('fuera_de_servicio', 'Fuera de Servicio')], default='disponible', max_length=25)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fleet_vehiculo',
                'indexes': [models.Index(fields=['estado'], name='fleet_vehic_estado_727f11_idx')],
            },
        ),
    ]
