# Generated by Django 6.0.4 on 2026-04-23 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('exceso_horas', 'Exceso de Horas'), ('mantenimiento_proximo', 'Mantenimiento Próximo'), ('zona_prohibida', 'Zona Prohibida'), ('bajo_rendimiento', 'Bajo Rendimiento'), ('falla_sensor', 'Falla en Sensor')], max_length=40)),
                ('mensaje', models.TextField()),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('resuelta', models.BooleanField(default=False)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.conductor')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contrato')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehiculo')),
            ],
            options={
                'db_table': 'fleet_alerta',
                'indexes': [models.Index(fields=['vehiculo'], name='fleet_alert_vehicul_b78fd5_idx'), models.Index(fields=['resuelta'], name='fleet_alert_resuelt_df359a_idx'), models.Index(fields=['tipo'], name='fleet_alert_tipo_5fea50_idx'), models.Index(fields=['-fecha_generacion'], name='fleet_alert_fecha_g_c5446c_idx')],
            },
        ),
    ]
