# Generated by Django 6.0.4 on 2026-04-23 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingresos', 'Ingresos'), ('mantenimiento', 'Mantenimiento'), ('rentabilidad', 'Rentabilidad'), ('horas_conductor', 'Horas Conductor')], max_length=40)),
                ('parametros', models.JSONField(default=dict)),
                ('resultado', models.JSONField(blank=True, null=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('exportado', models.BooleanField(default=False)),
                ('ruta_archivo', models.CharField(blank=True, max_length=500, null=True)),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fleet_reporte',
                'indexes': [models.Index(fields=['tipo'], name='fleet_repor_tipo_abdc08_idx'), models.Index(fields=['fecha_generacion'], name='fleet_repor_fecha_g_00ec27_idx')],
            },
        ),
    ]
