# Generated by Django 6.0.4 on 2026-04-23 05:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], default='preventivo', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('km_al_momento', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('proximo_km', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('proximo_fecha', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mantenimientos', to='vehicles.vehiculo')),
            ],
            options={
                'db_table': 'fleet_mantenimiento',
                'indexes': [models.Index(fields=['vehiculo'], name='fleet_mante_vehicul_5c3f25_idx'), models.Index(fields=['estado'], name='fleet_mante_estado_2e1ffa_idx'), models.Index(fields=['fecha'], name='fleet_mante_fecha_67c9fd_idx')],
            },
        ),
    ]
