# Generated by Django 6.0.4 on 2026-04-23 05:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=25, unique=True)),
                ('tipo_tarifa', models.CharField(choices=[('hora', 'Hora'), ('dia', 'Día'), ('km', 'Kilómetro')], default='dia', max_length=10)),
                ('tarifa_valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('km_inicial', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('km_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('costo_subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('costo_penalizaciones', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='activa', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contratos', to='drivers.conductor')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contratos', to='vehicles.vehiculo')),
            ],
            options={
                'db_table': 'fleet_contrato',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=25, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('exportada', models.BooleanField(default=False)),
                ('ruta_pdf', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='factura', to='contracts.contrato')),
            ],
            options={
                'db_table': 'fleet_factura',
            },
        ),
        migrations.CreateModel(
            name='Penalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('exceso_horas', 'Exceso de horas'), ('zona_prohibida', 'Zona prohibida'), ('daño', 'Daño'), ('otro', 'Otro')], max_length=50)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalizaciones', to='contracts.contrato')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fleet_penalizacion',
            },
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['estado'], name='fleet_contr_estado_26f431_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['vehiculo'], name='fleet_contr_vehicul_1707f8_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['conductor'], name='fleet_contr_conduct_04e375_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['fecha_inicio'], name='fleet_contr_fecha_i_d7b650_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['fecha_emision'], name='fleet_factu_fecha_e_049003_idx'),
        ),
        migrations.AddIndex(
            model_name='penalizacion',
            index=models.Index(fields=['contrato'], name='fleet_penal_contrat_864eee_idx'),
        ),
    ]
